credentials:
  usernames:
    amzl.hub:
      name: "Usuario AMZL"
      password: $2b$12$OgXrMkU7sDpK26M7H2bKieKZ0ceLQau2LdrhR4SWo9Q4k7i2XTXBC 
cookie:
  expiry_days: 30
  key: "alguna_clave_secreta"
  name: "amzl_cookie"
